version: "3.8"

services:
  basedatos:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Guatemala
      POSTGRES_DB: tienda
    volumens:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - umgnet
    ports:
      - "5432:5432"

  pgadmin:
  image: dpage/pgadmin4:latest
  container_name: pgadmin
  environment:
    PGADMIN_DEFAULT_EMAIL: admin@admin.com
    PGADMIN_DEFAULT_PASSWORD: password
  ports:
    - "8080:80"
  depends_on:
    - basedatos
  networks:
    - umgnet

networks: umgnet

volumes: postgres_data




      
